---
name: "Spring-petclinic-CI"
pool:
  name: Default

trigger: none

pr:
  - main
variables:
  - name: java_Home
    value: /usr/lib/jvm/java-17-openjdk-amd64
  - name: maven_Home
    value: /opt/apache-maven-3.9.9

stages:
  - stage: CI
    displayName: SpringPetclinic-DayBuild
    jobs:
      - job: Build
        displayName: SpringPetclinic-mavenBuild
        steps:
          - task: Maven@4
            inputs:
              mavenPOMFile: pom.xml
              goals: clean package
              mavenVersionOption: path
              mavenDirectory: ${{ variables.maven_Home }}
              mavenSetM2Home: true
              javaHomeOption: path
              jdkDirectory: ${{ variables.java_Home }}
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              testRunTitle: 'spc_test'

          - task: CopyFiles@2
            inputs:
              contents: '**/*.jar'
              TargetFolder: $(Build.ArtifactStagingDirectory)
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'snapshot'