---
name: "Spring-petclinic-CI"
pool:
  vmImage: "ubuntu-24.04"

trigger: none

pr:
  - main

parameters:
  - name: "javaversion"
    type: string
    default: 1.17
    values:
      - '1.17'
      - '1.11'
      - '1.10'
      - '1.9'
      - '1.8'

stages:
  - stage: CI
    displayName: SpringPetclinic-DayBuild
    jobs:
      - job: Build
        displayName: SpringPetclinic-mavenBuild
        steps:
          - task: Maven@4
            inputs:
              mavenPOMFile: pom.xml
              goals: clean package
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              testRunTitle: 'spc_test'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: "${{ parameters.javaversion }}"

          - task: CopyFiles@2
            inputs:
              contents: '**/*.jar'
              TargetFolder: $(Build.ArtifactStagingDirectory)
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'snapshot'